### ISSUE TITLE
Difference between this project & Location project

### ISSUE THREAD

**Issue by simonayzman** [voyage11/GettingLocationWhenSuspended#1]
This code resource is really amazing. Thanks so much for it. I do have a question though. I've been going over the two projects that you've put up about constantly receiving location updates when in the background (Location) and even when killed/terminated/suspended (GettingLocationWhenSuspended). Having looked over the code for both projects, I was just wondering how they were different. The code here seems to be refactored without LocationTracker and BackgroundTaskManager. Also, in this project, you're saving the information directly to the device, whereas in 'Location' you're sending it to a server. Despite these differences, I wanted to know which project design you think is better and why? And if anything, what would you change altogether?

(In context, I'm going to write an app that asks for the device's location every 5 - 15 seconds and stores that data using CoreData for later manipulation and analysis)

**Comment by voyage11** [comment]
No problem. There are 2 different location manager instances which are doing 2 different things.

Location Project: Getting the location when the app is on the foreground or in the background for a fixed time interval. Because the background time for iOS 7 and above is only 3 minutes, the trick would be refreshing background time before it expires. For this project, whenever the iOS or the user kills the app, the location manager will not work anymore.

GettingLocationWhenSuspended Project: It does not need BackgroundTaskManager because it is not running in the background. It has to be a different location manager instance from the First project because one location manager can only run only location related function. The app will not get the location in a fixed interval. The app will only get location when the device has moved for over 500 meters and at most 1 location update in every 5 minutes. When the user is not moving, the location will not be updated.

As for other question, the decision to store the location coordinates locally or send to server is really based on the purpose of your app. I just developed the solution to show different examples on what it can do. You may use it whichever way that makes sense for you.

Getting location every 5 - 15 seconds would be too much. It will drain the battery very very fast. I would suggest you to increase the time interval.

You should read more from my blog post to understand the details:
http://mobileoop.com/background-location-update-programming-for-ios-7
http://mobileoop.com/getting-location-updates-for-ios-7-and-8-when-the-app-is-killedterminatedsuspended

**Comment by simonayzman** [comment]
Really helpful answer. Thank you! So if I wanted my application to save
location always, regardless of the state, I would have to create some sort
of combination of the code from your two projects, yes?

Also, did you mean that each locationManager can only do ~one~ task at a
time, or what did you mean?

**Comment by voyage11** [comment]
Yes, You will have to combine the solutions of the 2 projects if you want to make the best of the location manager. 

The function of location manager to get the location updates:-
1. [myLocationManager startUpdatingLocation];
2. [myLocationManager startMonitoringSignificantLocationChanges];

You can only choose one. You may not use both at the same time for the same location manager instance. That's the reason it needs 2 different instances of location manager if you want to get the location in the fixed interval (foreground and background) while monitoring the significant location changes (suspended mode).

**Comment by Darkhorse-Fraternity** [comment]
Hi ,Thanks for your demo ,  it does not work when i used your project and it be killed .（ i used xocde 6.3）.  
i found the methods
if ([launchOptions objectForKey:UIApplicationLaunchOptionsLocationKey]) {}   never enter

**Comment by mobisaily** [comment]
Hi,

I am facing the same scenario like the one simonayzman is facing. How did u solve the problem?
